### DISCUSSION TITLE
Ideas for Broker's concept of sequences

### DISCUSSION THREAD

**Discussion by JacobCallahan** [SatelliteQE/broker#150] [Ideas]
In this discussion, I'd like to solicit feedback on the design for Broker sequences. These sequences should be thought of as a series of broker commands with accompanying arguments. I'd like to keep the scope as small as possible, but still be useful.
Let's try not to replicate Ansible here :)

The general structure will be a YAML format, with each action being a single element of the overall sequence
```yaml
- checkout:
    workflow: "deploy-sat-jenkins"
    deploy_sat_version: "7.0"
    note: "miscellaneous arguments"
- checkout:
    nick: rhel7
    count: 3
    sequential: False
- checkin:
    args: [-1]
```

```yaml
- multi_execute:
    nicks:
    - nick1
    - nick2
    ignore_errors: True
```
or run all nicks
```yaml
- multi_execute:
    nicks: all
    sequential: False 
```
Another consideration is the ability to run not just one, but multiple sequences from a specified directory.
If we went this path, then we could specify that scenario files adopt the `.scenario` extension. This would make identification in a directory much easier.
One important part may be either consolidating output and/or inventory contents. The inventory would be relatively easy to do, but output would be a little more tricky.
```yaml
- with_inventory: "temp_inventory.yaml"
- checkout:
    nick: sat610
```
With this, we're flirting on adding more complexity than needed since it would look better to define the file like
```yaml
inventory: "temp_inventory.yaml"
scenario:
- checkout:
    nick: sat610
```
That opens up the specification to more meta manipulation..

Calling scenarios should maintain Broker's current parity between CLI and Library usage.
```
broker scenario multi_execute
```
With the equivalent library call
```python
Broker.scenario("multi_execute")
```
However, CLI usage also bring up the possibility of passing additional arguments at runtime for steps, much like we currently can with nicks.
Let's consider the following example:
```yaml
scenarios:
    - deploy_pr:
        - checkout:
            workflow: deploy-sat
            deploy_sat_version: stream
        - execute:
            workflow: install_upstream_pr
            repository: <tbd>
            pr_number: <tbd>
```
How would we allow a user to specify the repository and pr_number arguments at runtime?
```
broker scenario deploy_pr --repository foreman --pr_number 1234
```
This is an option, but what if multiple scenarios use the same arguments? Perhaps a way to specify step would be needed, but that seems messy. Alternatively, we could allow users to specify jinja-like variables that a scenario could accept.
```yaml
scenarios:
    - deploy_pr:
        - checkout:
            workflow: deploy-sat
            deploy_sat_version: stream
        - execute:
            workflow: install_upstream_pr
            repository: "{{ repo_name }}"
            pr_number: "{{ pr_num }}"
```
