### ISSUE TITLE
AttributeError is raised when loading host with more complex data in `_broker_args` `from_inventory`

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/broker#164]
Have the following `inventory.yaml`:
```yaml
- _broker_args:
    cdn_rhn_password: supersecret
    cdn_rhn_username: thisismyaccount
    cdn_rhsm_pool_id: some-cool-pool-id
    deploy_rhel_version: 8.6.0
    fqdn: dhcp-2-206.oh.no.fqdn.has.leaked
    host_type: host
    name:
    - ogajduse-is-cool-RHEL-8.6.0-20220420.3
    os_distribution: RedHat
    os_distribution_version: '8.6'
    reported_devices:
      nics:
      - lo
      - eth0
    rhel_compose_id: RHEL-8.6.0-20220420.3
    rhel_compose_repositories:
    - baseurl: http://foo.bar/repo1/os
      description: repo1
      file: os_repo.repo
      name: repo1
    - baseurl: http://foo.bar/repo2/os
      description: repo2
      file: os_repo.repo
      name: repo2
    sat_ansible_version: 2.9
    sat_xy_version: '6.11'
    template: RHEL-8.6.0-20220420.3
    tower_inventory: satlab-what-02-inventory
    workflow: deploy-satellite-rhel-cmp-template
  _broker_provider: AnsibleTower
  hostname: dhcp-2-206.oh.no.fqdn.has.leaked
  name: ogajduse-is-cool-RHEL-8.6.0-20220420.3
  type: host
```

And run:
```python
from broker import Broker
Broker().from_inventory(filter='something')
```

or

```sh
ipython -c 'from broker import Broker; Broker().from_inventory(filter="something")'
```

The following traceback is generated:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [1], in <module>
----> 1 from broker import Broker; Broker().from_inventory(filter="something")

File ~/repos/broker/broker/broker.py:345, in Broker.from_inventory(self, filter)
    340 def from_inventory(self, filter=None):
    341     """Reconstruct one or more hosts from the local inventory
    342 
    343     :param filter: A broker-spec filter string
    344     """
--> 345     inv_hosts = helpers.load_inventory(filter=filter)
    346     return [self.reconstruct_host(inv_host) for inv_host in inv_hosts]

File ~/repos/broker/broker/helpers.py:207, in load_inventory(filter)
    203 inventory_file = settings.BROKER_DIRECTORY.joinpath(
    204     settings.settings.INVENTORY_FILE
    205 )
    206 inv_data = load_file(inventory_file, warn=False)
--> 207 return inv_data if not filter else inventory_filter(inv_data, filter)

File ~/repos/broker/broker/helpers.py:115, in inventory_filter(inventory, raw_filter)
    113 for host in inventory:
    114     flattened_host = flatten_dict(host, separator=".")
--> 115     eval_list = [
    116         eval(rf.test.format(haystack=flattened_host[rf.haystack], needle=rf.needle))
    117         for rf in resolved_filter
    118         if rf.haystack in flattened_host
    119     ]
    120     if eval_list and all(eval_list):
    121         matching.append(host)

File ~/repos/broker/broker/helpers.py:118, in <listcomp>(.0)
    113 for host in inventory:
    114     flattened_host = flatten_dict(host, separator=".")
    115     eval_list = [
    116         eval(rf.test.format(haystack=flattened_host[rf.haystack], needle=rf.needle))
    117         for rf in resolved_filter
--> 118         if rf.haystack in flattened_host
    119     ]
    120     if eval_list and all(eval_list):
    121         matching.append(host)

AttributeError: 'NoneType' object has no attribute 'haystack'
```

#### Additional info
```
$ broker --version
Version: 0.2.6
```
