### ISSUE TITLE
[RFE] allow custom environmental variables to be passed to containers/hosts

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/broker#174]
SSIA.

My specific use case would be to control external logging service (promtail) behavior (enabled/disabled, target loki server, ...)

**Comment by rplevka** [comment]
One of the ideas of @JacobCallahan on how to approach this was to update the [_sanitize_create_args](https://github.com/SatelliteQE/broker/blob/master/broker/binds/containers.py#L93) method to pass any non-recognized docker/podman run keyword args as env vars to the target container rather than stripping them off

**Comment by rplevka** [comment]
so the env vars seem to be already supported by the [underlaying lib](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run), here's a snippet of a nick yaml that sets `LOKI_URL` var:

```
  rhel8_docker_promtail:
    container_host: "ubi8:rplevka"
    environment:
      LOKI_URL: "http://foo.bar/baz"
```
or, alternatively, a list of strings can be used:

```
  rhel8_docker_promtail:
    container_host: "ubi8:rplevka"
    environment:
      - "LOKI_URL=http://foo.bar/baz"
```
