### ISSUE TITLE
settings.logging.file_level is not honored

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/broker#223]
Having the following in `broker_settings.yaml`, nothing above the `INFO` level appears in `broker.log`.

```yaml
logging:
  console_level: info
  file_level: trace
```

Thanks @lpramuk for discovering it!
