### ISSUE TITLE
use entry-points to look up ssh backends

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [SatelliteQE/broker#361]
currently https://github.com/SatelliteQE/broker/blob/7dc516e6c228bd14693a14ec5f9744273f5964f1/broker/session.py#L38-L57
hardcodes the names of ssh backends and acts on global configruation

i recommend to load the backend types via [package metadata](https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/#using-package-metadata)

```toml
[project.entry-points.'broker.ssh.session']
ansible-pylibssh = "broker.binds.pylibssh:Session"
ssh2-python = "broker.binds.ssh2:Session"
ssh2-python312 = "broker.binds.ssh2:Session"
hussh = "broker.binds.hussh:Session"

[project.entry-points.'broker.ssh.interactive_shell']
ssh2-python = "broker.binds.ssh2:InteractiveShell"
ssh2-python312 = "broker.binds.ssh2:InteractiveShell"

```

```python

def make_session(settings, kwargs):
    from importlib.metadata import entry_points
    SessionKlass = entry_points(group="broker.ssh.session", name=settings.SSH.BACKEND)[0]
    return SessionKlass(**kwargs)
```
