### ISSUE TITLE
Add a possibility to have multiple providers of the same type

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/broker#81]
Having a possibility to choose from multiple providers of the same type, defined in the _broker_settings.yaml_,  would be handy.

The initial idea of possible _broker_settings.yaml_ design containing multiple `AnsibleTower` providers:
```yaml
inventory_file: "inventory.yaml"
default_provider: at-instance1
AnsibleTower:
  - provider_nick: at-instance1 
    base_url: https://my-at-instance1.com/
    username: admin
    password: awesomepassword1
  - provider_nick: at-instance2 
    base_url: https://my-at-instance2.com/
    username: admin
    password: awesomepassword2
```

**Comment by bherrin3** [comment]
@ogajduse how would you want to choose between which `provider_nick` is active?

I am not sure I would always want `broker checkin --all` to delete all my VMs in all ATs... as that could be redundant inventories and give false job failures.

I am assuming a `default` would be good and being able to select a secondary would be more ideal?

`broker checkin --all provider:secondary`?

**Comment by JacobCallahan** [comment]
@ogajduse how about this?
```yaml
AnsibleTower:
  - nick: at-instance1
    default: True
    base_url: https://my-at-instance1.com/
    username: admin
    password: awesomepassword1
  - provider_nick: at-instance2 
    base_url: https://my-at-instance2.com/
    username: admin
    password: awesomepassword2
```

usage could look like: `broker checkout --nick rhel7 --AnsibleTower at-instance2`
